version: '3.9'

x-vmangos-shared-conf: &vmangos-shared-conf
  # environment:

  volumes:
    - "./etc:/opt/etc:rw"
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "./server:/opt/server:rw"
    - "${WOW_PATH}:/opt/wow:rw"
  restart: unless-stopped
  tty: true

x-build-shared-conf: &build-shared-conf
  dockerfile: Dockerfile
  args:
    USER_ID: ${USER_ID:-0}
    GROUP_ID: ${GROUP_ID:-0}

services:

  compile:
    image: vmangos:compile
    container_name: vmangos-compile
    env_file:
      - ./env/compile.env
      - ./env/shared.env
    build:
      context: containers/compile
      <<: *build-shared-conf
    <<: *vmangos-shared-conf
    restart: "no"
    profiles:
      - compile

  extract:
    image: vmangos:extract
    container_name: vmangos-extract
    env_file:
      - ./env/extract.env
    build:
      context: containers/extract
      <<: *build-shared-conf
    <<: *vmangos-shared-conf

  mangosd:
    image: vmangos:mangosd
    container_name: vmangos-mangosd
    build:
      context: containers/mangosd
      <<: *build-shared-conf
    ports:
      - "3443:3443"
      - "3444:3444" 
      - "7878:7878"
      - "8085:8085"
    <<: *vmangos-shared-conf
    
  mariadb:
    image: vmangos:mariadb
    container_name: vmangos-mariadb
    hostname: mariadb
    env_file:
      - ./env/mariadb.env
      - ./env/shared.env
    build:
      context: containers/mariadb
      <<: *build-shared-conf
    ports:
      - "3306:3306"
    <<: *vmangos-shared-conf

  phpmyadmin:
    image: phpmyadmin
    container_name: vmangos-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=pwd
    restart: "no"
    depends_on:
      - mariadb
    profiles:
      - dev

  realmd:
    image: vmangos:realmd
    container_name: vmangos-realmd
    build:
      context: containers/realmd
      <<: *build-shared-conf
    ports:
      - "3724:3724"
    <<: *vmangos-shared-conf

  web:
    image: vmangos:web
    container_name: vmangos-web
    build:
      context: containers/web
      <<: *build-shared-conf
    ports: 
      - "80:80"
    <<: *vmangos-shared-conf
    volumes:
      - "./www/htdocs:/htdocs:rw"
    profiles:
      - web

networks:
  default:
    name: vmangos-server-network
