version: '3.9'

services:

  compile:
    image: vmangos:compile
    env_file:
      - ./env/compile.env
    container_name: vmangos-compile
    build:
      context: containers/compile
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./server:/opt/server:rw"
      - "./etc:/opt/etc:rw"
      - "${WOW_PATH}:/opt/wow:rw"
    tty: true

  mangosd:
    image: vmangos:mangosd
    container_name: vmangos-mangosd
    build:
      context: containers/mangosd
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "3443:3443"
      # - "3444:3444" # Offline Chat 
      # - "7878:7878" # SOAP 
      - "8085:8085"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./server:/opt/server:rw"
    restart: unless-stopped
    tty: true

  mariadb:
    image: vmangos:mariadb
    env_file:
      - ./env/mariadb.env
    container_name: vmangos-mariadb
    hostname: mariadb
    build:
      context: containers/mariadb
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    # ports:
    #  - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./etc:/opt/etc:rw"
      - "./server:/opt/server:rw"
    restart: unless-stopped
    tty: true

  realmd:
    image: vmangos:realmd
    container_name: vmangos-realmd
    build:
      context: containers/realmd
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    ports:
      - "3724:3724"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./server:/opt/server:rw"
    restart: unless-stopped
    tty: true

networks:
  default:
    name: vmangos-server-network
